### PR TITLE
Add usage information and documentation to the README

### PR DESCRIPTION
**Pull request by spiralman**
@ustudio/dev Please review. I don't plan on cutting a release for this, since it doesn't have any code changes.

---
This change is [Reviewable](https://reviewable.io/reviews/ustudio/ustack-logging/2)

### CODE REVIEW

**Comment by tjensen** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/ustack-logging/2#-:-KdfXfwEz8z0Em0r0imW:bnfp4nl)*

**Comment by spiralman** [comment]
@tjensen Actually, found a bug in the example code, so updated it.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/ustack-logging/2#-:-KdhICjLDL3md7PvK_t5:bys9y91)*

**Comment by fearphage** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/ustack-logging/2)*

**Comment by fearphage** [comment]
@tjensen @spiralman Merging since it's only docs.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ustudio/ustack-logging/2#-:-KdhJgRM3ikwh4rjkz8j:bx2q0hq)*

**Pull request merged**
